### ISSUE TITLE
Create custom log destinations?

### ISSUE THREAD

**Issue by whitehat007** [wp-fail2ban/docs#1]
Now that Apple [no longer writes authentication events to a log file](https://discussions.apple.com/thread/4149679), fail2ban on my Mac can't read `LOG_AUTH` and so this plugin doesn't work. Is there a way to send events from your plugin to a custom log file?

**Comment by invisnet** [comment]
That's interesting.... I suggest you come over to the [forums](https://forums.invis.net) to discuss it - this isn't really the right venue.
